set softtabstop=2 expandtab shiftwidth=2 smarttab

set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'
Bundle 'Shougo/neocomplete.vim'
Bundle "marijnh/tern_for_vim"
Bundle 'Raimondi/delimitMate'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'pangloss/vim-javascript'
Bundle 'mxw/vim-jsx'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'tpope/vim-surround'
Bundle 'ervandew/ag'
Bundle 'Blackrush/vim-gocode'
Bundle 'slim-template/vim-slim.git'
Bundle 'plasticboy/vim-markdown'
Bundle 'tpope/vim-endwise.git'
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'bling/vim-airline'
Bundle 'ntpeters/vim-better-whitespace'
Bundle 'majutsushi/tagbar'
Bundle 'qpkorr/vim-bufkill'
Bundle 'yosssi/vim-ace'
Bundle 'fatih/vim-go'
Bundle 'scrooloose/syntastic'

call vundle#end()            " required
filetype plugin indent on    " required

let g:vim_markdown_folding_disabled=2

let g:jsx_ext_required = 0 " Enable jsx highlighting in js files

" Custom keybindings
nmap <Tab><Tab> :NERDTreeTabsToggle<CR>
nmap <Ctrl-p> :CtrlP .
nmap <F8> :TagbarToggle<CR>

set t_Co=256
syntax on
set background=dark
colorscheme jellybeans

set number
set list

let g:airline#extensions#tabline#enabled = 1 " Enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t' " Show just the filename
let g:nerdtree_tabs_open_on_console_startup = 1
let g:nerdtree_tabs_smart_startup_focus = 2
